<a href="https://colab.research.google.com/github/MINIVO2/Basics_of_Tf/blob/main/tebsorflow00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamentals of **tensorflow**



In [ ]:
#import tensorflow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


In [ ]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim


0

In [ ]:
#create a vector
vector = tf.constant([[10,10],
                      [7,10]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7, 10]], dtype=int32)>

In [ ]:
vector.ndim


2

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[3.,4.], [5.,4.],[3.,7.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 4.],
       [5., 4.],
       [3., 7.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [9,10,11]],
                     [[12,13,14],
                      [16,171,17]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [  9,  10,  11]],

       [[ 12,  13,  14],
        [ 16, 171,  17]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what we have created so far:-

*scalar : a single number
*vector : a number with direction (eg: wind speed and direction)
*matrix : a 2-Dimensional array of number(when n can be any number , qa 0 dimensional tensor is a scalar, a 1 dimensional is a vector)


#CREATING TENSORS WITH tf.variable

In [ ]:
changeable_tensor = tf.Variable([10,7], dtype = tf.int16)
unchangable_tensor = tf.constant([10,7])
changeable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int16, numpy=array([10,  7], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#to change an item in changable tensor using .assign
changeable_tensor[0].assign(7)
#we cannot change unchangable_tensor as it is constant

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int16, numpy=array([7, 7], dtype=int16)>

note: Rarely in practice will you need to decide whether to use tf.constant or tf.variable to create


## **CREATING RANDOM TENSORS**

In [ ]:
 random_1= tf.random.Generator.from_seed(42)#set seed for reproducibility
 random_1 = random_1.normal(shape=(3,2))
 random_2= tf.random.Generator.from_seed(2)#set seed for reproducibility
 random_2 = random_2.normal(shape=(3,2))
 random_3 = tf.random.Generator.from_seed(32)
 random_3 = random_3.normal(shape=(3,2))

 random_3,random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182,  1.585549 ],
        [ 0.4356279,  0.2364518],
        [-0.1589871,  1.302304 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [ ]:
X1 = tf.random.Generator.from_seed(42)
X1 = X1.uniform(shape = (3,2), minval = 0, maxval = 10, dtype = tf.int32)
X1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 7],
       [6, 8],
       [6, 1]], dtype=int32)>

In [ ]:
F1 = tf.random.Generator.from_seed(42)
F1= F1.uniform(shape= [50])
F1

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
       0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ,
       0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732,
       0.8857763 , 0.2179842 , 0.29115117, 0.03953862, 0.8136791 ,
       0.8139852 , 0.52180684, 0.12496924, 0.5488483 , 0.7755773 ,
       0.6184403 , 0.24936223, 0.89341843, 0.28422844, 0.70332646,
       0.2622137 , 0.4432162 , 0.466465  , 0.05981874, 0.40098202,
       0.69292355, 0.1284684 , 0.22770369, 0.33691216, 0.5329138 ,
       0.5914326 , 0.21738243, 0.5322075 , 0.05148339, 0.03951418,
       0.41866875, 0.78939915, 0.04384279, 0.96955836, 0.49116182],
      dtype=float32)>

In [ ]:
F2 = tf.constant(np.random.randint(0,50, size = 80))
F2

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([34,  9,  2, 21, 32,  0, 11, 40, 24, 16, 31, 43,  1, 32, 22, 38, 33,
       33, 10, 31, 16, 34,  5, 27, 32, 32, 27, 46, 32,  6, 49,  7, 47, 33,
       28,  4, 43, 42, 47, 38, 15, 46, 48,  2, 16, 28, 28, 35, 23, 24, 17,
       23, 48,  4, 21, 22, 10, 24, 49, 29, 30,  1,  2, 21, 34,  7, 17, 19,
       21, 15, 23, 43, 24, 30, 28, 42,  3, 20, 15, 19])>

In [ ]:
tf.random.set_seed(42)
tf.random.uniform(shape = [50])

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## shuffle the order of elements in a tensor


In [ ]:
#shuffle a tensor( valuable for when you want to shuffle your data so inherent order dosent affect your leaarning)
not_shuffle = tf.constant([[10,2,3],
                           [5,17,34],
                           [19,23,56]])
not_shuffle.ndim
shuffle = tf.random.shuffle(not_shuffle)


it looks like if we want our shuffled tensors to be in particular/same order, we've got to use the global level random seed as well as the operation level random seed:

In [ ]:
#shuffle our non_shuffled tensor
tf.random.set_seed(41) # (global level seed)by changing the seed you can shuffle the values in constant order but in random
tf.random.shuffle(not_shuffle,seed = 42)# (operation level seed)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 23, 56],
       [ 5, 17, 34],
       [10,  2,  3]], dtype=int32)>

In [ ]:
#exercise
shuffle_1 = tf.Variable([[2,4],
                         [4,5],
                         [6,7]])
tf.random.set_seed(42) #global
tf.random.shuffle(shuffle_1,seed =42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 5],
       [6, 7]], dtype=int32)>

it looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as operation level random seed

#OTHER WAYS TO CREATE TENSORS

In [ ]:
#create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeroes
tf.zeros([10,7], dtype = tf.int32)

<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

# **Turn numpy arrays into tensors**

the main difference between numpy arrays and tensorflow tensors is that tensors can run on a gpu (faster numerical computing)

In [ ]:
#numpy arrays into tensors
import numpy as np
np_A= np.arange(0,25, dtype = 'int32')
#X = tf.constant([scalar])
#y= tf.constant([vector])
np_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(np_A, shape = (5,5)) # shape should be equal to total number of element
# if there are 0-25 elements then it should multiply upto 25 or 1-25 then multiply up to 24
#change shape
B = tf.constant(np_A)
A,B

(<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(25,), dtype=int32, numpy=
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tensors
shape - the length(number of elements)
of each of the dimensions of a tensor. tensor.shape

rank - the number of tensor dimensions. A scalar has rank 0, vector has rank 1, matirx has rank 2, and tensor has rank n. tensor.ndim

Axis or dimension - A particular dimension of a tensor.  tensor[0], tensor[:,1]

size - total number of items in the tensor tf.size

In [ ]:
#create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor).numpy() #shape = 2*3*4*5 = 120

(TensorShape([2, 3, 4, 5]), 4, 120)

In [ ]:
#get various attributes
print("Datatype of every element: ", rank_4_tensor.dtype)
print("number of dimensions :", rank_4_tensor.ndim)
print("shape of tensor: ",rank_4_tensor.shape)
print("Elements along 0th axis",rank_4_tensor.shape[0])
print("Elements along last axis",rank_4_tensor.shape[-1]) #last axis
print("tottal number of elements",tf.size(rank_4_tensor))
print("tottal number of elements",tf.size(rank_4_tensor).numpy()) #.numpy gives the exact number of elements

Datatype of every element:  <dtype: 'float32'>
number of dimensions : 4
shape of tensor:  (2, 3, 4, 5)
Elements along 0th axis 2
Elements along last axis 5
tottal number of elements tf.Tensor(120, shape=(), dtype=int32)
tottal number of elements 120


# Indexing Tensors
tensors can be indexed just like Python lists

In [ ]:
#get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list = [[1,2,3,4],
             [5,6,7,8]]
some_list[:2]

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
#first element fromm each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1] # : means print everything of that dimension


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create rank 2 dimension
rank_2_tensor = tf.constant([[10,7],
                             [7,10]])
rank_2_tensor.shape

TensorShape([2, 2])

In [ ]:
#to get the last element of each row
rank_2_tensor[:,-1].numpy()

array([ 7, 10], dtype=int32)

In [ ]:
#add ann extra dimension
rank_3_tensor= rank_2_tensor[...,tf.newaxis] #... means every axis before the last one or [:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_3_tensor, axis = -1) #-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 7]],

        [[10]]]], dtype=int32)>

In [ ]:
#expand 0 axis
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]]], dtype=int32)>

# **Manipulating tensors(tensor operations)**
+,-,*,/

In [ ]:
#add value to tensors
tensors = tf.constant([[10,7],
                       [7,10]])
tensors + 10 #original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]], dtype=int32)>

In [ ]:
#the only way to change tensor
tensors = tensors + 10
tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]], dtype=int32)>

In [ ]:
#multiplication
tensors * 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2000, 1700],
       [1700, 2000]], dtype=int32)>

In [ ]:
#subtraction
tensors - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#tensor in-built operator
tf.multiply(tensors, 10) #it is much faster for gpu
tf.add(tensors, 10) #etc...

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [27, 30]], dtype=int32)>

# **Matric Multiplication**

there are two rules for matrices to multiply


*   the inner dimensions must match
* the resulting matrix has the shape of the outer dimensions



In [ ]:
#matrix multiplication
print(tensors)
tf.matmul(tensors,tensors) #applicable for same shape

tf.Tensor(
[[20 17]
 [17 20]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[689, 680],
       [680, 689]], dtype=int32)>

In [ ]:
#matric multiplication with @
tensors @ tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[689, 680],
       [680, 689]], dtype=int32)>

In [ ]:
X = tf.random.Generator.from_seed(42)
X = X.uniform(shape = (3,2), minval = 0, maxval = 10, dtype = tf.int32)
Y = tf.random.Generator.from_seed(42)
Y = Y.uniform(shape = (3,2), minval = 0, maxval = 20, dtype = tf.int32)
# array([[ 3, 17],
#         [ 6, 18],
#         [ 6,  1]], dtype=int32)>,
#  <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
#  array([[3, 7],
#         [6, 8],
#         [6, 1]], dtype=int32)>)


In [ ]:
#try to multiply tensors of same shape
X.shape, Y.shape #the outer dimensions dont match (3,2) (3,2)
Y1 =tf.reshape(Y, shape = (2,3))



In [ ]:
#try to multiply X with reshaped Y1
# cannot use Y cause it remains in original shape
tf.matmul(X,Y1)  # 3 X 3
#or
X @ tf.reshape(Y, shape= (2,3)) # making the outer layer same and multiplying it with @

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[135,  93,  25],
       [162, 150,  44],
       [ 36, 108,  37]], dtype=int32)>

In [ ]:
#try changing shape x
X1 = tf.reshape(X, shape = (2,3))
X1 @ Y #2 X 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 87, 183],
       [ 66, 245]], dtype=int32)>

In [ ]:
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 7],
        [6, 8],
        [6, 1]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 6],
        [7, 8, 1]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 7, 6],
        [8, 6, 1]], dtype=int32)>)

In [ ]:
#transpose multiplication
tf.matmul(tf.transpose(X),Y) #transpose basically changes the axis

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81, 165],
       [ 75, 264]], dtype=int32)>

# **The dot product**

Matrix multiplication is also reffered to as the dot product:

You can perform matrix multiplication using:
*tf.matmul()
*tf.tensordot()[link text](https://)

In [ ]:
#perfom dot product with X and y
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81, 165],
       [ 75, 264]], dtype=int32)>

In [ ]:
#perform matrix multiplicatio n between X and Y (transpose)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[128, 144,  25],
       [154, 180,  44],
       [ 35,  54,  37]], dtype=int32)>

In [ ]:
#tensordot with reshaped Y
tf.tensordot(X, tf.reshape(Y, shape = (2,3)), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[135,  93,  25],
       [162, 150,  44],
       [ 36, 108,  37]], dtype=int32)>

In [ ]:
#reshape X and Y (same values above)
tf.matmul(X, tf.reshape(Y,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[135,  93,  25],
       [162, 150,  44],
       [ 36, 108,  37]], dtype=int32)>

In [ ]:
#check values of y , reshape Y, and trnspose Y

print("Normal Y: ",Y)
print("\n")
print("reshaped Y: ", tf.reshape(Y, shape = (2,3)))
print("\n")
print("Transpose Y : ",tf.transpose(Y))

Normal Y:  tf.Tensor(
[[ 3 17]
 [ 6 18]
 [ 6  1]], shape=(3, 2), dtype=int32)


reshaped Y:  tf.Tensor(
[[ 3 17  6]
 [18  6  1]], shape=(2, 3), dtype=int32)


Transpose Y :  tf.Tensor(
[[ 3  6  6]
 [17 18  1]], shape=(2, 3), dtype=int32)


**generally when performing matrix mul on 2 tensors and one of the axes dosent line up you with transpose instead of reshape to satisfy multiplication rules**

# Changing the datatype of tensor

In [ ]:
B = tf.constant([1.4, 1.7])
B.dtype

tf.float32

In [ ]:
C = tf.constant([4,5])
C.dtype

tf.int32

In [ ]:
#Change from float32 to float16 (reduced precesion)
D = tf.cast(B, dtype = tf.int16)
D.dtype

tf.int16

In [ ]:
#change from int32 to int16
E = tf.cast(C, dtype = tf.int16)
E.dtype

tf.int16

In [ ]:
E = tf.cast(E, dtype = tf.float32)
E.dtype

tf.float32

## Agregatting Tensors
Condesing them from multiple values to a smaller amount of values

In [ ]:
# get the absolute values
D = tf.constant([-7,-10])
tf.abs(D) #take all negative values and return them to negative values


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#lets go through following forms of aggregation
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
#create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([50,  0, 61, 87, 58, 78,  4,  6, 83, 49, 70, 32, 27, 95, 22, 35, 63,
       43, 62, 66, 73,  0, 43, 82, 48, 71, 53, 44, 27, 67, 84, 94, 80,  5,
       96, 63, 65, 67, 29,  4,  0, 45, 97, 99, 37, 57, 44, 54, 98, 62])>

In [ ]:
# find the min of a tensor
tf.reduce_min(E)
#for numpy it is
#np.min(E)


<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
#find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [ ]:
#find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2679>

In [ ]:
#find varience
import tensorflow_probability as tfp
tfp.stats.variance(E)
#or
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=817.6036>

In [ ]:
#find standard deviation

tf.math.reduce_std(tf.cast(E, dtype= tf.float32)) #if you get typeerror check your datatype

<tf.Tensor: shape=(), dtype=float32, numpy=28.59377>

# Positional Maximum and minimum of a tensor (returns the index of maximum and minimum value)



In [ ]:
#create a new tensor for finding positional minimum and maximum
F = tf.random.Generator.from_seed(42)
F = F.uniform(shape= [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
       0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ,
       0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732,
       0.8857763 , 0.2179842 , 0.29115117, 0.03953862, 0.8136791 ,
       0.8139852 , 0.52180684, 0.12496924, 0.5488483 , 0.7755773 ,
       0.6184403 , 0.24936223, 0.89341843, 0.28422844, 0.70332646,
       0.2622137 , 0.4432162 , 0.466465  , 0.05981874, 0.40098202,
       0.69292355, 0.1284684 , 0.22770369, 0.33691216, 0.5329138 ,
       0.5914326 , 0.21738243, 0.5322075 , 0.05148339, 0.03951418,
       0.41866875, 0.78939915, 0.04384279, 0.96955836, 0.49116182],
      dtype=float32)>

In [ ]:
#Find positional maximum
tf.argmax(F) # np.argmax()

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 1, 5, 9, 3])>

In [ ]:
#index of the largest value
F[tf.argmax(F)] #gives out the element of maximum
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.96955836>

In [ ]:
#find positional minimum
tf.argmin(F) #np.argmin

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [ ]:
F[tf.argmin(F)]
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.039514184>

# Squeezing a tensor (removing all single dimensions)

In [ ]:
#create a tensor to get started
tf.random.set_seed(42) #to keep the random values same
G = tf.constant(tf.random.uniform(shape = [50]), shape=[1,1,1,1,50] )
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
squeeze= tf.squeeze(G)
squeeze.shape

TensorShape([50])

# One hot encoding tensors

In [ ]:
#create a list of indices
some_list = [0,1,2,3]# could be red, green, blue, purple
depth = 4 #total number of dimensions
#one hot encode our list of indices
tf.one_hot(some_list, depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one hot encoding
tf.one_hot(some_list, depth, on_value="My name is Ayush", off_value="My name is not Ayush")
#on_value = 1, of_value = 0

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'My name is Ayush', b'My name is not Ayush',
        b'My name is not Ayush', b'My name is not Ayush'],
       [b'My name is not Ayush', b'My name is Ayush',
        b'My name is not Ayush', b'My name is not Ayush'],
       [b'My name is not Ayush', b'My name is not Ayush',
        b'My name is Ayush', b'My name is not Ayush'],
       [b'My name is not Ayush', b'My name is not Ayush',
        b'My name is not Ayush', b'My name is Ayush']], dtype=object)>

#square root, log Squaring


In [ ]:
T= tf.range(1,10)



In [ ]:
#squaring
tf.square(T)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#squareroot (method requires non int type)
tf.math.sqrt(tf.cast(T, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#find log
tf.math.log(tf.cast(T, dtype= tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Numpy with tensors
tensorflow interacts beutifully with numpy arrays

In [ ]:
#create a tensor directly from a numoy arrays
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert tensor back to numpy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#the deafult type of each are slightly different
numpy_J = tf.constant(np.array([1.,2.,3.]))
tensor_J = tf.constant([1.,2.,3.])
#datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

#Finding access to GPU


In [ ]:
import tensorflow as tf
tf.config.list_logical_devices() #first change the runtime to GPU in Runtime

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


If you have access to a CUDA - enabled GPU, Tensorflow will automatically use it whenever possible